ALTER TABLE "indentItems" ALTER COLUMN "indentedQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "indentItems" ALTER COLUMN "approvedQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "purchaseOrderItems" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "tableList" ALTER COLUMN "minQuantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "inventory" ALTER COLUMN "inStockQuantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "inventory" ALTER COLUMN "usedQuantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "washingUnit" ALTER COLUMN "bhusaQuantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "washingUnitItems" ALTER COLUMN "reqQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "washingUnitItems" ALTER COLUMN "issueQuantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "rp" ALTER COLUMN "consumedQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "rp" ALTER COLUMN "producedQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "rp" ALTER COLUMN "loomQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "rp" ALTER COLUMN "lamQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "rp" ALTER COLUMN "tapeQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "rp" ALTER COLUMN "tarpQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "rp" ALTER COLUMN "plantWasteConsumed" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "rp" ALTER COLUMN "rpLumps" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "rpItems" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "quantity" ALTER COLUMN "producedQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "quantity" ALTER COLUMN "usedQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "quantity-for" ALTER COLUMN "usedQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "tapeItem" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "tapePlant" ALTER COLUMN "tapeQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "tapePlant" ALTER COLUMN "tapeWaste" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "tapePlant" ALTER COLUMN "tapeLumps" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "tapePlantConsumedItem" ALTER COLUMN "qty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "loom" ALTER COLUMN "tapeQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "loom" ALTER COLUMN "fabricQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "loom" ALTER COLUMN "loomWaste" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "loomItem" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "lamItem" ALTER COLUMN "quantity" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "lamination" ALTER COLUMN "fabricQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "lamination" ALTER COLUMN "lamFabricQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "lamination" ALTER COLUMN "lamWaste" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "tarpaulin" ALTER COLUMN "lamFabricQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "tarpaulin" ALTER COLUMN "tarpaulinQty" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "tarpaulin" ALTER COLUMN "tarpWaste" SET DATA TYPE double precision;--> statement-breakpoint
ALTER TABLE "tarpaulinItem" ALTER COLUMN "quantity" SET DATA TYPE double precision;